### ISSUE TITLE
add actionbar 

### ISSUE THREAD

**Issue by yhdesai** [Shipr-Hub/Shipr-Community-Android#82]

**Comment by Jantzilla** [comment]
I noticed this issue when preparing to create a new issue to discuss the possibility of an app bar.
I feel that it would help the overall UX by providing a background for the "chat filter" (general, help, android), so that the text bubbles be larger and extend the full width of the device.

If this is still something that is desired, I would be happy to offer a PR. 

**Original**

![shipr-original](https://user-images.githubusercontent.com/35611020/55938485-1b0bed80-5c01-11e9-96e1-ae5fcf7fd752.png)

**Mock Update**

![shipr-change](https://user-images.githubusercontent.com/35611020/55938515-2c54fa00-5c01-11e9-8f41-5a9c5d091e0e.png)

**Comment by yhdesai** [comment]
Sounds good!

**Comment by Jantzilla** [comment]
@yhdesai Let me know if you'd recommend any changes.
